/* Author: Adrian le Bas
			
		   Twitter: @adrianleb

		   Jquery 1.7.1
		   Plugins:

		   LetteringJS
		   thats it...

*/window.log=function(){log.history=log.history||[];log.history.push(arguments);if(this.console){arguments.callee=arguments.callee.caller;var a=[].slice.call(arguments);typeof console.log=="object"?log.apply.call(console.log,console,a):console.log.apply(console,a)}};(function(a){function b(){}for(var c="assert,clear,count,debug,dir,dirxml,error,exception,firebug,group,groupCollapsed,groupEnd,info,log,memoryProfile,memoryProfileEnd,profile,profileEnd,table,time,timeEnd,timeStamp,trace,warn".split(","),d;d=c.pop();)a[d]=a[d]||b})(function(){try{console.log();return window.console}catch(a){return window.console={}}}());(function(a){function b(b,c,d,e){var f=b.text().split(c),g="";if(f.length){a(f).each(function(a,b){g+='<span class="'+d+(a+1)+'">'+b+"</span>"+e});b.empty().append(g)}}var c={init:function(){return this.each(function(){b(a(this),"","char","")})},words:function(){return this.each(function(){b(a(this)," ","word"," ")})},lines:function(){return this.each(function(){var c="eefec303079ad17405c889e092e105b0";b(a(this).children("br").replaceWith(c).end(),c,"line","")})}};a.fn.lettering=function(b){if(b&&c[b])return c[b].apply(this,[].slice.call(arguments,1));if(b==="letters"||!b)return c.init.apply(this,[].slice.call(arguments,0));a.error("Method "+b+" does not exist on jQuery.lettering");return this}})(jQuery);$(document).ready(function(){function p(a,b){var c=$(this).scrollLeft(),d=$(window).width(),e=$(document).width();if(c>3900&&!o){j.addClass("not");o=!0}else if(c<3900&&o){j.removeClass("not");o=!1}b?$("html, body").animate({scrollLeft:"+=320"},500):a&&$("html, body").animate({scrollLeft:"-=320"},500);return c}var a=$("#mainButton"),b=$(window),c=$("section"),d=$("#cardHolder"),e,f=$(".flipper"),g=$("#nav"),h=$(".lChar"),i=$(".lWord"),j=$("#end"),k,l=0,m=$("#navLeft"),n=$("#navRight"),o;h.lettering();i.lettering("words");d.addClass("init");g.addClass("init");n.on("click",function(a){p(!1,!0);a.preventDefault()});m.on("click",function(a){p(!0,!1);a.preventDefault()});$(window).scroll(function(){p(!1,!1)});a.toggle(function(a){c.addClass("mason");g.addClass("mason");p();a.preventDefault()},function(a){c.removeClass("mason");g.removeClass("mason");a.preventDefault()});f.toggle(function(a){$(this).parent().addClass("flip");a.preventDefault()},function(a){$(this).parent().removeClass("flip");a.preventDefault()})});